sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
cache:
  apt: true
  pip: false
addons:
  apt:
    packages:
      - libcurl4-gnutls-dev
      - librtmp-dev
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install 'pytest == 2.7.2'; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then pip install pytest; fi
  - pip install pytest-mock pycurl flake8 tox-travis
  - python setup.py clean --all
  - python setup.py install
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8 emburse; fi
  - python -W always setup.py test
  - py.test tests
notifications:
  email: false